version: '3'
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["/usr/local/bin/myapi/wait-for-db.sh", "db", "/usr/local/bin/myapi/init.sh"]

  db:
    build: ./docker/mariadb/
    environment:
      MYSQL_ROOT_PASSWORD: mysecretrootpassword
      MYSQL_DATABASE: easysubmit_db
      MYSQL_USER: main_user
      MYSQL_PASSWORD: mysecretuserpassword
    ports:
      - 3306:3306
    restart: always